#!/usr/bin/env python3
"""
Generate RAG-format fine-tuning examples from legal documents.

Runs the same ingestion + chunking pipeline the API uses (so chunks match
what retrieval will actually produce), then asks a local Ollama model to
write natural Turkish questions grounded in each chunk. Each record is
built in the exact BAĞLAM-block format ``api.prompts.build_rag_prompt``
uses at inference time, so the fine-tuned model trains on the same input
shape it will see in production.

A configurable fraction of examples are "negatives": a real question paired
with an UNRELATED chunk's context, labeled with the canonical
``api.prompts.NOT_FOUND_ANSWER`` sentence. These are what teach the
zero-hallucination refusal behavior — skipping them will leave the model
inclined to answer from context that doesn't actually contain the answer.

⚠ This is synthetic data generated by a local LLM. Spot-check a sample of
the output before using it to fine-tune — the generator model can still
produce a question/answer pair that drifts from the source chunk.

Usage
-----
    # Preview how many chunks qualify, without calling Ollama
    python scripts/generate_finetune_data.py --dry-run

    # Generate from sample_data/ (default), 2 questions per chunk
    python scripts/generate_finetune_data.py

    # Generate from a specific directory, cap at 20 chunks (quick smoke test)
    python scripts/generate_finetune_data.py --docs-dir uploads --limit 20

Output is written to a NEW file (default ``hukuk_veri_seti_rag.jsonl``) —
it does not touch your existing curated ``hukuk_veri_seti.jsonl``. Merge
manually once you've reviewed the output, e.g.:

    cat hukuk_veri_seti.jsonl hukuk_veri_seti_rag.jsonl > merged.jsonl
"""

from __future__ import annotations

import argparse
import json
import logging
import random
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional

import httpx

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from api.config import settings
from api.prompts import NOT_FOUND_ANSWER, format_context_block
from legal_doc_ingestion.ingestion import LegalDocumentIngestor
from legal_doc_ingestion.vectorization.chunker import LegalSemanticChunker, TextChunk

logging.basicConfig(level=logging.INFO, format="%(asctime)s │ %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger("gen_finetune_data")

_SUPPORTED_EXTS = {".pdf", ".docx", ".rtf"}

_GEN_PROMPT_TEMPLATE = """\
Aşağıda bir hukuki belgeden alınmış tek bir madde/bölüm metni var. Bu metne \
dayanarak, bir kullanıcının doğal şekilde sorabileceği {n} FARKLI ve ÇEŞİTLİ \
Türkçe soru üret. Her soru için, cevabı YALNIZCA verilen metinden alınmış, \
doğal ve anlaşılır bir cevap yaz. Cevapta metinde olmayan hiçbir bilgi \
uydurma.

Başlık: {heading}
Metin:
\"\"\"
{text}
\"\"\"

Yanıtını SADECE şu JSON formatında ver, başka hiçbir açıklama ekleme:
[{{"question": "...", "answer": "..."}}, ...]
"""

_JSON_ARRAY_RE = re.compile(r"\[.*\]", re.DOTALL)

_HEADING_RE = re.compile(
    r"(?im)^(MADDE|Madde|ARTICLE|Article|GEÇİCİ\s+MADDE|Geçici\s+Madde)\s"
)


def _find_source_files(docs_dir: Path) -> List[Path]:
    if not docs_dir.exists():
        return []
    return sorted(
        p for p in docs_dir.iterdir()
        if p.is_file() and p.suffix.lower() in _SUPPORTED_EXTS
    )


def _collect_chunks(docs_dir: Path, min_chars: int) -> List[TextChunk]:
    """Ingest + chunk every supported document in ``docs_dir``."""
    ingestor = LegalDocumentIngestor()
    chunker = LegalSemanticChunker(
        overlap_ratio=settings.CHUNK_OVERLAP,
        min_chunk_chars=settings.CHUNK_MIN_CHARS,
        max_chunk_chars=settings.CHUNK_MAX_CHARS,
    )

    all_chunks: List[TextChunk] = []
    for filepath in _find_source_files(docs_dir):
        try:
            result = ingestor.ingest(filepath)
        except Exception as exc:
            logger.warning("Atlandı (ingest hatası) %s: %s", filepath.name, exc)
            continue

        chunks = chunker.chunk(result.full_cleaned_text(), source_id=filepath.name)
        all_chunks.extend(chunks)
        logger.info("%s → %d chunk", filepath.name, len(chunks))

    # Only keep chunks with a real article/section heading and enough content
    # to ground a meaningful question — skips preambles and stray fragments.
    qualifying = [
        c for c in all_chunks
        if c.section_heading and _HEADING_RE.match(c.section_heading) and c.char_count >= min_chars
    ]
    logger.info(
        "Toplam %d chunk, %d tanesi soru üretimi için uygun (başlıklı + yeterli uzunlukta).",
        len(all_chunks), len(qualifying),
    )
    return qualifying


def _call_ollama(client: httpx.Client, prompt: str, model: str) -> Optional[str]:
    try:
        resp = client.post(
            "/api/generate",
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": 0.6, "num_predict": 800},
            },
        )
        resp.raise_for_status()
        return resp.json().get("response", "")
    except Exception as exc:
        logger.warning("Ollama isteği başarısız: %s", exc)
        return None


def _parse_qa_pairs(raw_response: str) -> List[Dict[str, str]]:
    match = _JSON_ARRAY_RE.search(raw_response)
    if not match:
        return []
    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError:
        return []
    pairs = []
    for item in data:
        q = (item.get("question") or "").strip()
        a = (item.get("answer") or "").strip()
        if q and a:
            pairs.append({"question": q, "answer": a})
    return pairs


def _build_context_block(chunk: TextChunk) -> str:
    return format_context_block([{
        "section_heading": chunk.section_heading,
        "source_id": chunk.source_id,
        "text": chunk.text,
    }])


def generate(
    *,
    docs_dir: Path,
    questions_per_chunk: int,
    negative_ratio: float,
    min_chars: int,
    limit: Optional[int],
    model: str,
    base_url: str,
    seed: int,
    dry_run: bool,
) -> List[Dict[str, str]]:
    rng = random.Random(seed)
    chunks = _collect_chunks(docs_dir, min_chars)
    if limit:
        chunks = chunks[:limit]

    if dry_run:
        for c in chunks[:10]:
            logger.info("  ör: [%s] %s (%d karakter)", c.source_id, c.section_heading, c.char_count)
        return []

    if not chunks:
        logger.error("Uygun chunk bulunamadı — --docs-dir yolunu kontrol edin.")
        return []

    records: List[Dict[str, str]] = []
    positives: List[tuple] = []  # (question, answer, chunk) for negative pairing later

    with httpx.Client(base_url=base_url, timeout=120.0) as client:
        for i, chunk in enumerate(chunks, 1):
            logger.info("[%d/%d] %s | %s", i, len(chunks), chunk.source_id, chunk.section_heading)
            prompt = _GEN_PROMPT_TEMPLATE.format(
                n=questions_per_chunk, heading=chunk.section_heading, text=chunk.text
            )
            raw = _call_ollama(client, prompt, model)
            if not raw:
                continue
            pairs = _parse_qa_pairs(raw)
            if not pairs:
                logger.warning("  JSON parse edilemedi, atlandı.")
                continue

            context_block = _build_context_block(chunk)
            for pair in pairs:
                records.append({
                    "instruction": pair["question"],
                    "input": context_block,
                    "output": pair["answer"],
                })
                positives.append((pair["question"], chunk))

    # --- Negative examples: real question + unrelated chunk's context ---
    n_negatives = int(len(positives) * negative_ratio)
    if n_negatives and len(chunks) > 1:
        for _ in range(n_negatives):
            question, own_chunk = rng.choice(positives)
            other_chunk = rng.choice([c for c in chunks if c.source_id != own_chunk.source_id] or chunks)
            if other_chunk is own_chunk:
                continue
            records.append({
                "instruction": question,
                "input": _build_context_block(other_chunk),
                "output": NOT_FOUND_ANSWER,
            })

    rng.shuffle(records)
    return records


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--docs-dir", type=Path, default=Path("sample_data"), help="Kaynak belge klasörü (default: sample_data)")
    parser.add_argument("--output", type=Path, default=Path("hukuk_veri_seti_rag.jsonl"), help="Çıktı dosyası (default: hukuk_veri_seti_rag.jsonl — mevcut veri setinizi ETKİLEMEZ)")
    parser.add_argument("--questions-per-chunk", type=int, default=2)
    parser.add_argument("--negative-ratio", type=float, default=0.25, help="Pozitiflere oranla 'bulunamadı' örneği oranı (default: 0.25)")
    parser.add_argument("--min-chunk-chars", type=int, default=80)
    parser.add_argument("--limit", type=int, default=None, help="İşlenecek maksimum chunk sayısı (test için)")
    parser.add_argument("--model", type=str, default=settings.OLLAMA_MODEL)
    parser.add_argument("--ollama-url", type=str, default=settings.OLLAMA_BASE_URL)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--dry-run", action="store_true", help="Ollama'yı çağırmadan sadece uygun chunk sayısını göster")
    args = parser.parse_args()

    records = generate(
        docs_dir=args.docs_dir,
        questions_per_chunk=args.questions_per_chunk,
        negative_ratio=args.negative_ratio,
        min_chars=args.min_chunk_chars,
        limit=args.limit,
        model=args.model,
        base_url=args.ollama_url,
        seed=args.seed,
        dry_run=args.dry_run,
    )

    if args.dry_run or not records:
        return

    with args.output.open("w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    n_neg = sum(1 for r in records if r["output"] == NOT_FOUND_ANSWER)
    logger.info(
        "%d kayıt yazıldı → %s (%d pozitif, %d negatif/'bulunamadı')",
        len(records), args.output, len(records) - n_neg, n_neg,
    )
    logger.warning(
        "⚠ Bu veriler bir LLM tarafından üretildi — eğitimde kullanmadan önce "
        "bir örneklem üzerinden gözle kontrol edin."
    )


if __name__ == "__main__":
    main()
